# Generated by Django 4.0.4 on 2022-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_banner_button_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bunner_button_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
