# Generated by Django 4.0.4 on 2022-04-23 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0007_homepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('menu', wagtail.core.fields.StreamField([('menus', wagtail.core.blocks.StructBlock([('title_menu', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('title_url', wagtail.core.blocks.URLBlock(help_text='Add additional text', required=True))]))])),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='left_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_menus', to='home.leftmenu'),
        ),
    ]
