# Generated by Django 4.0.4 on 2022-04-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_contact_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
