# Generated by Django 4.0.4 on 2022-05-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_rename_artistprofile_servicepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
